version: '3.8'

services:
  web:
    image: vgssy/music-streaming-api
    ports:
      - "8080:80"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

