version: '3.8'

services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres:/docker-entrypoint-initdb.d
      - /home/deploy/.env
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: production
    working_dir: /rails
    volumes:
      - .:/rails
      - /rails/public/assets # To prevent deleting precompiled assets.
      - bundle:/usr/local/bundle
      - /home/deploy/.env

    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/ats_production
      ASSUME_SSL: false
      FORCE_SSL: false
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle:
