
service: music-streaming-api

image: vgssy/music-streaming-api

servers:
    - 176.114.90.118

proxy: 
  ssl: true
  host: api.example.com
  # Proxy connects to your container on port 80 by default.
  # app_port: 3000

# Credentials for your image host.
registry:  
  username: vgssy
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: deploy

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: debug

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"


# Configure the image builder.
builder:
  arch: amd64

accessories:
  db:
    image: postgres:14
    host: 176.114.90.118
    port: 5432
    env:
      clear:
        POSTGRES_USER: Vgssy
        POSTGRES_DB: MusicServise
        POSTGRES_HOST: 176.114.90.118
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - data:/var/lib/postgresql/data
    
  